Group-10/Class Write-Up.md, Group-10/Team Agreement.md
Team agreement and class write-up committed as markdown files.
=> [Bellman] Initial Team Agreement and Class Write-Ups

Group-05/CMakeLists.txt, Group-05/main.cpp, Group-05/src/Datum.cpp, Group-05/src/Datum.h
Created initial Datum Class. Methods implemented:
- Constructors
- AsString/Double
- IsString/Double
- SetStringValue
- SetDoubleValue
- GetVariant
- GetString/Double
Also implemented:
- If an invalid string tries to convert into a double, returns NaN
- If NaN (double) tries to convert into a string, returns an empty string
TODO:
- Implement  operations (+,-,*,/,>,<,=, etc)
- Better testing/test framework
Notes:
1) Since we don't have a testing framework yet, I added some very basic tests to main (Felt weird to push code without testing). Will need to move and improve the tests once we pick a testing framework. Also, probably remove main at some point (I think).
2) I'm not sure how we want to set up/organize the project. I just added a few folders to help organize it a bit. Can change …
=> Hamilton - Datum Class 

.gitignore, Group-01/.clang-format, Group-01/Distribution/README.md, Group-01/Graph/Edge.hpp, Group-01/Graph/Graph.cpp, Group-01/Graph/Graph.hpp, Group-01/Graph/README.md, Group-01/Graph/Vertex.hpp, Group-01/Graph/main.cpp, Group-01/GraphPosition/README.md, Group-01/Random/README.md, Group-01/TeamAgreement.md, Group-01/WeightedSet/README.md
Updating my distribution class
=> Distribution back to date

Group-09/TextBox/FormattedText.cpp, Group-09/TextBox/FormattedText.hpp, Group-09/TextBox/TextBox.hpp, tests/Group-09/Makefile, tests/Group-09/TestFormattedText.cpp, tests/Group-09/TestTextBox.cpp
Added TextBox and FormattedText classes, and implemented unit tests for both classes.
=> added TextBox and FormattedText classes and test files

Group-05/main.cpp, Group-05/src/Datum.cpp, Group-05/src/Datum.h
Completed:
1) Added Datum overloaded functions for +, -, *, /, ==.
2) Fixed trailing 0s for double to string conversion.
3) Updated Datum based on the Professor's suggestions
3.1) Removed SetStringValue() and SetDoubleValue()
3.2) Added operator= for Datum, string, and double.
Notes:
1) For +, -, *, /, it calculates the value for two Datum doubles. Otherwise, returns NaN (Two Strings or one double and one string) 
2) For ==, it works for two double Datums or two string Datums. Also, due to double imprecision, needed an epsilon. I picked a random, small number. May want to choose a different one.
3) Didn't fully test all the functions in main.cpp yet.
TODO:
1) Need to discuss how we want to implement >, >=, <, <=. Do we mix and match strings and doubles? Do we separate them? I don't know …
=> hamilton - hamilton-datum-feature PR

Group-05/main.cpp
Just needed to compile with DataGrid.cpp and add a test for ReferenceVector
=> Group 5 feat: adding test for updating vector and uncommenting old tests

ComboManager.h, Group-10/Classes/BruteForceOptimizer.h
=> Bellman brute force optimizer

Group-09/Image/image.cpp, Group-09/Image/image.hpp, Group-09/Image/main.cpp, tests/Group-09/TestImage.cpp
Merging changes from Image Class and Test for Image Class
=> Liskov merge

Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.h, Group-09/WebLayout/index.html, Group-09/WebLayout/main.cpp
Compiling with main creates a weblayout with varying sizes of textboxes/images. Next step is configuring positioning of elements and sequentially binding multiple web layouts together.
=>  Liskov web layout initial class development

Group-01/Distribution/Distribution.hpp, Group-01/Distribution/README.md, Group-01/Distribution/main.cpp
Added the main.cpp and Distribution header where I implemented the Uniform and Binomial distributions as well as the getters. I also updated the specs slightly.
=> Building the basic Distribution Class

Group-10/Classes/ComboManager.h, tests/Group-10-Tests/Makefile, tests/Group-10-Tests/TestComboManager.cpp
Added namespace to ComboManager and changed variable names to match.
Added Test file for ComboManager where all tests are passing at the moment.
=> Added new changes to ComboManager and added the Test cpp file for it.

Group-05/main.cpp, Group-05/src/Datum.cpp, Group-05/src/Datum.h, tests/Group-05/DatumTests.cpp, tests/Group-05/Makefile
Completed:
1) Added tests for the Datum.cpp class (Also created a Makefile for it) 
2) Added asserts throughout the Datum.cpp class
3) Added default constructors for copy, destructor, move, and move assignment. 
4) There was a bug where strings that started with numerical values would convert into a double. For example, "123Hello" would convert into a double with the value of 123. I fixed the issue and these strings should be NaN now.
=> [hamilton] hamilton-datum-tests PR - Datum tests and asserts

Group-10/Classes/MemoFunction.cpp, Group-10/Classes/MemoFunction.h, tests/Group-10-Tests/Makefile, tests/Group-10-Tests/TestMemoFunction.cpp
This branch has changes to the MemoFunction.h file, and the Makefile in Group-10 tests. It adds a TestMemoFunction.cpp file to the tests folder, and adds the test name into the Makefile. When built locally, all the tests pass.
=> Bellman memo function test

Group-10/Classes/MemoryFactory.h, tests/Group-10-Tests/Makefile, tests/Group-10-Tests/TestMemoryFactory.cpp
I added the test suite for MemoryFactory, as well as building up additional functionality for the class. The Makefile file order was switched as I noticed the program terminated as soon as a test case fails, and currently not all of my test cases are passing for full functionality.
=> Test Cases and Class Edits for MemoryFactory

Group-09/Image/image.hpp, Group-09/TextBox/TextBox.hpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.h, Group-09/WebLayout/main.cpp, tests/Group-09/TestWebLayout.cpp
@allienello @miabodenhorn I had to add == operator functions to Image and Textbox when I switched from the temporary structs to your classes. Feel free to change it in any way you think is best. I just had to throw it in quickly to get my test cases to work :D
=> Liskov WebLayout | Testing + Image/Textbox integration

Group-07/Data/sample.csv, Group-07/Team07Library/DataFileManager.cpp, Group-07/Team07Library/DataFileManager.h, tests/Group-07/DataFileManagerTest.cpp
Added Tests/Asserts. Tests not fully complete due to classes being incomplete, will be completed next week along with the classes.
=> Team07 DFM Merge

Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.h, Group-09/WebLayout/index.html, Group-09/WebLayout/main.cpp, tests/Group-09/TestWebLayout.cpp
Proper placement of images and textboxes
=> Liskov web layout

Group-10/Classes/StaticVector.h
Added comments to StaticVector.h
=> Added comments to StaticVector

Group-04/bin/main.cpp, Group-04/lib/BitVector.hpp, Group-04/lib/CseString.hpp, tests/Group-04/Makefile
Merge changes prompted by review
=> Group 4 bitvect

Group-09/TextBox/FormattedText.cpp, Group-09/TextBox/FormattedText.hpp, Group-09/TextBox/TextBox.hpp, tests/Group-09/Makefile, tests/Group-09/TestFormattedText.cpp, tests/Group-09/TestTextBox.cpp
- Moved default member variable initialization from config structs to class members.
- Implemented proper copy/move constructors & assignment operators for both classes.
- Standardized `getFormattedText()` to return a reference for efficiency.
- Added in some asserts throughout code.
- Updated test cases to pass.
=> Refactored TextBox & FormattedText Classes

Group-09/EventQueue/EventQueue.cpp, Group-09/EventQueue/EventQueue.hpp, tests/Group-09/TestEventQueue.cpp
Added asserts to EventQueue peek and pop. Added ID set attribute to EventQueue. Updated unit tests
=> EventQueue Asserts and Unit Tests

Group-10/Classes/ComboManager.h
Added STL algorithms to functions instead of for loops.
Made a couple extra helper functions for better modularity.
Made more clear comments.
=> Made Changes to ComboManager

Group-01/Distribution/Distribution.hpp, Group-01/Distribution/README.md, tests/Group1/Distribution/Distribution.cpp
Updated after code reviews polishing off code and adding comments.
=> Updating Code after Review

Group-09/EventManager/EventManager.cpp, Group-09/EventManager/EventManager.hpp, tests/Group-09/TestEventManager.cpp
- Added RepeatEvent functionaity to update repeat if already repeated event is called
- Added comments to EventManager
- Added testcase for empty EventManager
- Added const to function parameters when applicable.
=> EventManager: Updated based on code reviews

Group-10/Advanced Class Write-Up.md, tests/Group-10-Tests/TestBruteForceOptimizer.cpp, tests/Group-10-Tests/TestComboManager.cpp
Co-Authored by Blake Crimmons, Alex Mueller, Amery Johnson, and Ephraim Bennet
Currently planning on merging it into Bellman to prevent the extraneous changed files from previous Bellman commits, this can be folded into Bellman proper before the final merge or after depending on preferences.
=> Initial Advanced Class Specs & Tests

Group-05/src/DataGrid.cpp, Group-05/src/DataGrid.h, tests/Group-05/DataGridTests.cpp, tests/Group-05/Makefile
Completed:
1) Added constexpr to most of the column math methods 
2) Added NaN test cases for the comparison methods
=> [hamilton] DataGrid Updates

Group-01/GraphPosition/GraphPosition.hpp, tests/Group-01/Graph/Graph.cpp, tests/Group-01/GraphPosition/GraphPosition.cpp
Deleted some comments and made the comments the same throughout. Also modified some GraphPosition classes to use references instead of pointers.
=> Stroustrup code update (fixed comments and updated some pointers to references)

Group-09/WebLayout/ExportSlideDeck.cpp, Group-09/WebLayout/LoadSlideDeck.cpp, Group-09/WebLayout/index.html, Group-09/WebLayout/main.cpp
Refactored main.cpp and index.html to use the loading and saving methods properly
=> Updated load and save functionality

Group-09/Image/Image.cpp, Group-09/Image/main.cpp, Group-09/WebLayout/WebLayoutManager.cpp, Group-09/WebLayout/WebLayoutManager.hpp, Group-09/WebLayout/index.html
Mia added Image button functionality and fixed class based on reviews
=> Merging Liskov-Image 

Group-09/TextBox/TextBox.hpp, Group-09/WebLayout/EditTextbox.js, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayoutManager.cpp, Group-09/WebLayout/WebLayoutManager.hpp, Group-09/WebLayout/index.html
Textbox content can now be edited when a user double clicks a text box; to save/update, click out of the textbox or hit escape.
=> TextBox editing mode 

Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, Group-09/WebLayout/WebLayoutManager.cpp, Group-09/WebLayout/WebLayoutManager.hpp, Group-09/WebLayout/main.cpp
Added functionality to WebLayoutManager to drag items across screen to update position.
=> Liskov draggable item

Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp
I couldn't fully test this because the UI doesn't really have the option to toggle individual elements with events yet, but I believe the functions are like MOSTLY accurate or the right idea at least. Will add button to add event shortly to fully test this feature. 
#slay
=> Liskov - Ability to trigger individual elements visibility

Group-09/WebLayout/LoadSlideDeck.cpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, Group-09/WebLayout/WebLayoutManager.cpp
Removed loadPage function (rendering was moved into addImage/addTextbox function for easier usage) -> this was causing duplicate images
=> Liskov - fixed duplicate images

Group-05/src/CSVfile.cpp, Group-05/src/DataGrid.cpp, Group-05/src/DataGrid.h, tests/Group-05/CSVFileTests.cpp, tests/Group-05/DataGridTests.cpp
1) Changed DataGrid functions to PascalCase
=> Hamilton - DataGrid changes based on the code review

Group-09/WebLayout/WebLayoutManager.cpp
Just had to add some more checks to the file, errors are gone (for now)
=> Fixed errors appearing in browser console

Group-09/Makefile, Group-09/PresentationManager/PresentationEventManager.hpp, Group-09/PresentationManager/PresentationManager.hpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, Group-09/index.html, Group-09/js/EventListeners.hpp, Group-09/main.cpp
Added events for objects. Right click to add an event to a image or textbox
You can now choose timing for slide transitions
Events are saved and loaded in json. Events persist after leaving slide.
Fixed broken json loading and stack overflow for large json files
Fixed esc not working when browser was fullscreen
Small UI cleanups
Increased fps to 60
=> Event work

Group-09/Makefile, Group-09/PresentationManager/PresentationManager.hpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, Group-09/index.html, Group-09/js/EventListeners.hpp
Resizing of images + textbox
end of slide slide (for present mode) -- can be removed if no like
=> Liskov - RESIZEEXTRAVAGANZA

Group-09/PresentationManager/PresentationManager.hpp, Group-09/WebLayout/EditTextbox.js, Group-09/WebLayout/WebLayout.cpp, Group-09/index.html
You can now edit the color, size, and font of text for an entire textbox. Formatting menu appears when you double click it
=> Implemented formatting menu with textbox editing

Group-01/.clang-format, Group-01/main.cpp
Added better Usage of A* UI and fixed formatting.
=> Stroustrup distribution

Group-05/FinalApplication.cpp, Group-05/FinalApplication.h, Group-05/main.cpp, tests/Group-05/FinalApplicationTests.cpp
1) Updated function comments and added the class comment and more inline comments
2) Added const correctness to the fuctions
3) Added test cases more MathMenu, ComparisonMenu, and ManipuateGridMenu
=> [Hamilton] Additonal work on the main application

Group-05/FinalApplication.cpp, tests/Group-05/FinalApplicationTests.cpp
1) Added a negative index check to the GetColumn helper function
2) Errored checked and added tests for sort and main menu functions
=> [hamilton] Added more error checking and tests for the sort and main menus

Group-05/FinalApplication.cpp, tests/Group-05/FinalApplicationTests.cpp
1) Fixed bug where you were using m-dashes they displayed corrupted data
2) Added better spacing for the Main Menu and shows the grids you create
3) Added better printing for all the options
=> [Hamilton] main app printing updates

Group-05/FinalApplication.cpp, tests/Group-05/FinalApplicationTests.cpp
1) Added user input checks for resize, delete, and add (did NOT add checks for custom equation).
=> [hamilton] More user input handling

Group-05/FinalApplication.cpp, Group-05/FinalApplication.h
1) Used LLM to create a function that checks for a valid custom equation
=> 1) [hamilton] Added a valid custom equation check for the add function

Group-05/FinalApplication.cpp, tests/Group-05/FinalApplicationTests.cpp
1) Added tests for the resize, delete, and add menus
=> [Hamilton] Final tests

Group-05/FinalApplication.cpp, Group-05/FinalApplication.h, tests/Group-05/FinalApplicationTests.cpp
1) Simplified and improved readability for all functions (other than AddMenu). Mostly broke the large function into small functions.
=> [Hamilton] - Simplified and improved readability for all functions (except AddMenu)

Group-05/FinalApplication.cpp
1) Improved white space
2) Improved menus readability
3) Changed if/else statement to switch statement
=> [hamilton] - Final updates based on code review

Group-09/PresentationManager/PresentationManager.hpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, tests/Group-09/TestWebLayout.cpp, tests/Group-09/testingIndex.html
- Fixed WebLayout Testing (no index file existed to inject into)
- Added tests for additional functions in weblayout
- Fixed image size not saving correctly to json after being resized
- Added more doc comments
=> Liskov Small Bug Fixes

Group-09/EventManager/EventManager.hpp, Group-09/PresentationManager/PresentationEventManager.hpp, Group-09/PresentationManager/PresentationManager.hpp, Group-09/WebLayout/WebLayout.cpp, Group-09/WebLayout/WebLayout.hpp, tests/Group-09/MockClasses/MockPresentationEventManager.hpp, tests/Group-09/MockClasses/MockPresentationManager.hpp, tests/Group-09/MockClasses/MockWebLayout.cpp, tests/Group-09/TestApplication.cpp, tests/Group-09/TestEvent.cpp, tests/Group-09/TestEventManager.cpp, tests/Group-09/TestEventQueue.cpp
Updated application classes based on feedback.
=> Updated testcases based on Event id now being string. 

Group-09/TextBox/TextBox.hpp, Group-09/WebLayout/EditElement.js, Group-09/index.html
Added in suggestions from some reviews: different colored buttons (swap vs. Next slide), clamp max height for textboxes, draggable resizing for images, and a tool tip to 'double-click to edit' textboxes on hover
=> Code Review Edits

Group-09/EventQueue/EventQueue.hpp, Group-09/PresentationManager/PresentationEventManager.hpp, Group-09/WebLayout/WebLayout.hpp, tests/Group-09/TestWebLayout.cpp
- Some additional weblayout testcases
- Fixed adding duplicate events breaks things (now replaces old events)
- Added recoverable assert for pop and peek per review suggestion
- changed weblayout struct == operators to use ids instead of member variables
=> Liskov - Some review / bug changes
